/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_method = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_begin = 5,
  anon_sym_end = 6,
  anon_sym_SEMI = 7,
  anon_sym_COLON_EQ = 8,
  sym_identifier = 9,
  sym_str = 10,
  sym_char = 11,
  sym_hex = 12,
  sym_bits = 13,
  sym_dec = 14,
  anon_sym_true = 15,
  anon_sym_false = 16,
  sym_source_file = 17,
  sym_sourceItem = 18,
  sym_funcDef = 19,
  sym_block = 20,
  sym_statement = 21,
  sym_assignment = 22,
  sym_expr_stmt = 23,
  sym_expr = 24,
  sym_bool = 25,
  sym_literal = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_block_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_method] = "method",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_begin] = "begin",
  [anon_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON_EQ] = ":=",
  [sym_identifier] = "identifier",
  [sym_str] = "str",
  [sym_char] = "char",
  [sym_hex] = "hex",
  [sym_bits] = "bits",
  [sym_dec] = "dec",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_sourceItem] = "sourceItem",
  [sym_funcDef] = "funcDef",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_expr_stmt] = "expr_stmt",
  [sym_expr] = "expr",
  [sym_bool] = "bool",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_method] = anon_sym_method,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_begin] = anon_sym_begin,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_identifier] = sym_identifier,
  [sym_str] = sym_str,
  [sym_char] = sym_char,
  [sym_hex] = sym_hex,
  [sym_bits] = sym_bits,
  [sym_dec] = sym_dec,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_sourceItem] = sym_sourceItem,
  [sym_funcDef] = sym_funcDef,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_expr_stmt] = sym_expr_stmt,
  [sym_expr] = sym_expr,
  [sym_bool] = sym_bool,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_method] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_begin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_hex] = {
    .visible = true,
    .named = true,
  },
  [sym_bits] = {
    .visible = true,
    .named = true,
  },
  [sym_dec] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_sourceItem] = {
    .visible = true,
    .named = true,
  },
  [sym_funcDef] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 8,
  [19] = 19,
  [20] = 12,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 21,
  [31] = 28,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '"', 3,
        '\'', 30,
        '(', 35,
        ')', 36,
        '/', 6,
        '0', 61,
        ':', 7,
        ';', 41,
        'b', 11,
        'e', 19,
        'f', 8,
        'm', 12,
        't', 22,
        '{', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 3,
        '\'', 30,
        '/', 6,
        '0', 61,
        'b', 45,
        'e', 51,
        'f', 43,
        't', 53,
        '{', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(61);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '{') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(32);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 27:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(60);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 29:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(4);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_method);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_begin);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_begin);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_bits);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_dec);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(27);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_dec);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_method] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_begin] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_hex] = ACTIONS(1),
    [sym_bits] = ACTIONS(1),
    [sym_dec] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym_sourceItem] = STATE(14),
    [sym_funcDef] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_method] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_block] = STATE(9),
    [sym_statement] = STATE(3),
    [sym_assignment] = STATE(9),
    [sym_expr_stmt] = STATE(9),
    [sym_expr] = STATE(25),
    [sym_bool] = STATE(22),
    [sym_literal] = STATE(26),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_begin] = ACTIONS(9),
    [anon_sym_end] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [sym_str] = ACTIONS(15),
    [sym_char] = ACTIONS(15),
    [sym_hex] = ACTIONS(15),
    [sym_bits] = ACTIONS(15),
    [sym_dec] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_block] = STATE(9),
    [sym_statement] = STATE(4),
    [sym_assignment] = STATE(9),
    [sym_expr_stmt] = STATE(9),
    [sym_expr] = STATE(25),
    [sym_bool] = STATE(22),
    [sym_literal] = STATE(26),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [anon_sym_begin] = ACTIONS(9),
    [anon_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(13),
    [sym_str] = ACTIONS(15),
    [sym_char] = ACTIONS(15),
    [sym_hex] = ACTIONS(15),
    [sym_bits] = ACTIONS(15),
    [sym_dec] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym_block] = STATE(9),
    [sym_statement] = STATE(4),
    [sym_assignment] = STATE(9),
    [sym_expr_stmt] = STATE(9),
    [sym_expr] = STATE(25),
    [sym_bool] = STATE(22),
    [sym_literal] = STATE(26),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [anon_sym_begin] = ACTIONS(23),
    [anon_sym_end] = ACTIONS(26),
    [sym_identifier] = ACTIONS(28),
    [sym_str] = ACTIONS(31),
    [sym_char] = ACTIONS(31),
    [sym_hex] = ACTIONS(31),
    [sym_bits] = ACTIONS(31),
    [sym_dec] = ACTIONS(34),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
  },
  [STATE(5)] = {
    [sym_block] = STATE(9),
    [sym_statement] = STATE(6),
    [sym_assignment] = STATE(9),
    [sym_expr_stmt] = STATE(9),
    [sym_expr] = STATE(25),
    [sym_bool] = STATE(22),
    [sym_literal] = STATE(26),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_comment] = ACTIONS(3),
    [anon_sym_begin] = ACTIONS(9),
    [anon_sym_end] = ACTIONS(40),
    [sym_identifier] = ACTIONS(13),
    [sym_str] = ACTIONS(15),
    [sym_char] = ACTIONS(15),
    [sym_hex] = ACTIONS(15),
    [sym_bits] = ACTIONS(15),
    [sym_dec] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym_block] = STATE(9),
    [sym_statement] = STATE(4),
    [sym_assignment] = STATE(9),
    [sym_expr_stmt] = STATE(9),
    [sym_expr] = STATE(25),
    [sym_bool] = STATE(22),
    [sym_literal] = STATE(26),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [anon_sym_begin] = ACTIONS(9),
    [anon_sym_end] = ACTIONS(42),
    [sym_identifier] = ACTIONS(13),
    [sym_str] = ACTIONS(15),
    [sym_char] = ACTIONS(15),
    [sym_hex] = ACTIONS(15),
    [sym_bits] = ACTIONS(15),
    [sym_dec] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_dec,
    ACTIONS(44), 1,
      sym_identifier,
    STATE(22), 1,
      sym_bool,
    STATE(26), 1,
      sym_literal,
    STATE(32), 1,
      sym_expr,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(15), 4,
      sym_str,
      sym_char,
      sym_hex,
      sym_bits,
  [29] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 4,
      sym_str,
      sym_char,
      sym_hex,
      sym_bits,
    ACTIONS(46), 6,
      anon_sym_begin,
      anon_sym_end,
      sym_identifier,
      sym_dec,
      anon_sym_true,
      anon_sym_false,
  [47] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 4,
      sym_str,
      sym_char,
      sym_hex,
      sym_bits,
    ACTIONS(50), 6,
      anon_sym_begin,
      anon_sym_end,
      sym_identifier,
      sym_dec,
      anon_sym_true,
      anon_sym_false,
  [65] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 4,
      sym_str,
      sym_char,
      sym_hex,
      sym_bits,
    ACTIONS(54), 6,
      anon_sym_begin,
      anon_sym_end,
      sym_identifier,
      sym_dec,
      anon_sym_true,
      anon_sym_false,
  [83] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 4,
      sym_str,
      sym_char,
      sym_hex,
      sym_bits,
    ACTIONS(58), 6,
      anon_sym_begin,
      anon_sym_end,
      sym_identifier,
      sym_dec,
      anon_sym_true,
      anon_sym_false,
  [101] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 4,
      sym_str,
      sym_char,
      sym_hex,
      sym_bits,
    ACTIONS(62), 6,
      anon_sym_begin,
      anon_sym_end,
      sym_identifier,
      sym_dec,
      anon_sym_true,
      anon_sym_false,
  [119] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_method,
    STATE(19), 1,
      sym_funcDef,
    STATE(13), 2,
      sym_sourceItem,
      aux_sym_source_file_repeat1,
  [136] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_method,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_funcDef,
    STATE(13), 2,
      sym_sourceItem,
      aux_sym_source_file_repeat1,
  [153] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_begin,
    STATE(16), 1,
      sym_block,
  [163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_method,
  [171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_SEMI,
    ACTIONS(79), 1,
      anon_sym_COLON_EQ,
  [181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_method,
  [189] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_method,
  [197] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      anon_sym_method,
  [205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_SEMI,
  [212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_SEMI,
  [219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_SEMI,
  [226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
  [233] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_SEMI,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_SEMI,
  [247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_SEMI,
  [261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
  [268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_SEMI,
  [275] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_SEMI,
  [282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_SEMI,
  [289] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 29,
  [SMALL_STATE(9)] = 47,
  [SMALL_STATE(10)] = 65,
  [SMALL_STATE(11)] = 83,
  [SMALL_STATE(12)] = 101,
  [SMALL_STATE(13)] = 119,
  [SMALL_STATE(14)] = 136,
  [SMALL_STATE(15)] = 153,
  [SMALL_STATE(16)] = 163,
  [SMALL_STATE(17)] = 171,
  [SMALL_STATE(18)] = 181,
  [SMALL_STATE(19)] = 189,
  [SMALL_STATE(20)] = 197,
  [SMALL_STATE(21)] = 205,
  [SMALL_STATE(22)] = 212,
  [SMALL_STATE(23)] = 219,
  [SMALL_STATE(24)] = 226,
  [SMALL_STATE(25)] = 233,
  [SMALL_STATE(26)] = 240,
  [SMALL_STATE(27)] = 247,
  [SMALL_STATE(28)] = 254,
  [SMALL_STATE(29)] = 261,
  [SMALL_STATE(30)] = 268,
  [SMALL_STATE(31)] = 275,
  [SMALL_STATE(32)] = 282,
  [SMALL_STATE(33)] = 289,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_stmt, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_stmt, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_funcDef, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sourceItem, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_v2lang_test(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "v2lang_test",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
